//
// Created by Vlad on 19/08/2020.
//

#ifndef ENG1_VSHADERMODULEDEFS_H
#define ENG1_VSHADERMODULEDEFS_H

#define ENGINE_VULKAN_SHADER_CONFIG_SHADER_TYPE_VERTEX      "vert"
#define ENGINE_VULKAN_SHADER_CONFIG_SHADER_TYPE_GEOMETRY    "geom"
#define ENGINE_VULKAN_SHADER_CONFIG_SHADER_TYPE_TESSELATION "tess"
#define ENGINE_VULKAN_SHADER_CONFIG_SHADER_TYPE_FRAGMENT    "frag"
#define ENGINE_VULKAN_SHADER_CONFIG_SHADER_TYPE_UNDEFINED   "invalid"

#endif //ENG1_VSHADERMODULEDEFS_H
