//
// Created by loghin on 28.12.2021.
//

#ifndef C_ENG_VULKANAPIVALVEEXTENSIONDETAILS_HPP
#define C_ENG_VULKANAPIVALVEEXTENSIONDETAILS_HPP


#define __C_ENG_VULKAN_API_EXTENSION_VALVE_MUTABLE_DESCRIPTOR_TYPE_AVAILABLE false


#if defined(VK_VALVE_mutable_descriptor_type)

#undef __C_ENG_VULKAN_API_EXTENSION_VALVE_MUTABLE_DESCRIPTOR_TYPE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_VALVE_MUTABLE_DESCRIPTOR_TYPE_AVAILABLE true

#endif


#endif //C_ENG_VULKANAPIVALVEEXTENSIONDETAILS_HPP
