//
// Created by loghin on 04.02.2022.
//

#ifndef __C_ENG_VULKAN_API_POWER_VR_EXTENSION_DETAILS_HPP__
#define __C_ENG_VULKAN_API_POWER_VR_EXTENSION_DETAILS_HPP__


#define __C_ENG_VULKAN_API_POWER_VR_IMAGE_FORMAT_AVAILABLE false


#if defined ( VK_IMG_format_pvrtc )

#undef __C_ENG_VULKAN_API_POWER_VR_IMAGE_FORMAT_AVAILABLE
#define __C_ENG_VULKAN_API_POWER_VR_IMAGE_FORMAT_AVAILABLE true

#endif


#endif // __C_ENG_VULKAN_API_POWER_VR_EXTENSION_DETAILS_HPP__
