//
// Created by loghin on 01.01.2022.
//

#ifndef __C_ENG_VULKANCORECONFIG_HPP
#define __C_ENG_VULKANCORECONFIG_HPP

#define __C_ENG_VULKAN_CORE_VALIDATION_FEATURE_ENABLE_MAX_COUNT     128U
#define __C_ENG_VULKAN_CORE_VALIDATION_FEATURE_DISABLE_MAX_COUNT    128U

#endif //__C_ENG_VULKANCORECONFIG_HPP
