//
// Created by loghin on 28.12.2021.
//

#ifndef __C_ENG_VULKANAPIBLACKBERRYEXTENSIONDETAILS_HPP
#define __C_ENG_VULKANAPIBLACKBERRYEXTENSIONDETAILS_HPP


#define __C_ENG_VULKAN_API_EXTENSION_BLACKBERRY_QNX_SCREEN_SURFACE_AVAILABLE false


#if defined(VK_QNX_screen_surface)

#undef __C_ENG_VULKAN_API_EXTENSION_BLACKBERRY_QNX_SCREEN_SURFACE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_BLACKBERRY_QNX_SCREEN_SURFACE_AVAILABLE true

#endif


#endif //__C_ENG_VULKANAPIBLACKBERRYEXTENSIONDETAILS_HPP
