//
// Created by loghin on 01.01.2022.
//

#ifndef __C_ENG_VULKANCORECONFIG_HPP
#define __C_ENG_VULKANCORECONFIG_HPP

#define __C_ENG_VULKAN_CORE_VALIDATION_FEATURE_ENABLE_MAX_COUNT     32U
#define __C_ENG_VULKAN_CORE_VALIDATION_FEATURE_DISABLE_MAX_COUNT    32U

#define __C_ENG_VULKAN_CORE_LAYER_MAX_COUNT  64U
#define __C_ENG_VULKAN_CORE_LAYER_EXTENSION_MAX_COUNT  32U

#define __C_ENG_VULKAN_CORE_PHYSICAL_DEVICE_MAX_COUNT 8U

#define __C_ENG_VULKAN_CORE_FUNCTION_NAME_CREATE_DEBUG_MESSENGER    "vkCreateDebugUtilsMessengerEXT"
#define __C_ENG_VULKAN_CORE_FUNCTION_NAME_DESTROY_DEBUG_MESSENGER   "vkDestroyDebugUtilsMessengerEXT"

#endif //__C_ENG_VULKANCORECONFIG_HPP
