//
// Created by vladl on 08/08/2020.
//

#ifndef ENG1_VPHYSICALDEVICEDEFS_H
#define ENG1_VPHYSICALDEVICEDEFS_H

#define __VK_PHYSICAL_DEVICE_DEDICATED_GPU_VALUE_CONSTANT 100000U

#define __VK_PHYSICAL_DEVICE_PROPERTY_LIMIT_MAX_IMAGE_DIM_2D_SCALE 1U

#define __VK_PHYSICAL_DEVICE_TYPE_DEDICATED_GPU VulkanPhysicalDeviceType::VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU

#endif //ENG1_VPHYSICALDEVICEDEFS_H
