//
// Created by loghin on 27.12.2021.
//

#ifndef __C_ENG_VULKAN_API_DETAILS_HPP__
#define __C_ENG_VULKAN_API_DETAILS_HPP__

/**
 * Optional macros, define these in the project before importing any /API/vulkan headers
 *
 * __C_ENG_VULKAN_FORCE_NO_VULKAN
 * __C_ENG_VULKAN_FORCE_1_0
 * __C_ENG_VULKAN_FORCE_1_1
 * __C_ENG_VULKAN_FORCE_1_2
 * __C_ENG_VULKAN_FORCE_1_3
 * __C_ENG_VULKAN_FORCE_MAINLINE
 * __C_ENG_VULKAN_FORCE_NO_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_THIRD_PARTY_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_STANDARD_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_KHRONOS_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_AMD_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_APPLE_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_ARM_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_BLACKBERRY_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_GOOGLE_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_HUAWEI_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_INTEL_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_NVIDIA_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_POWERVR_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_QUALCOMM_EXTENSIONS
 * __C_ENG_VULKAN_FORCE_NO_VALVE_EXTENSIONS
 */

#define __C_ENG_VULKAN_BETA_EXTENSIONS_ENABLED false

#if defined ( VK_ENABLE_BETA_EXTENSIONS )

#undef __C_ENG_VULKAN_BETA_EXTENSIONS_ENABLED
#define __C_ENG_VULKAN_BETA_EXTENSIONS_ENABLED true

#endif


#if defined(__C_ENG_VULKAN_FORCE_NO_VULKAN)
#if !defined(__C_ENG_VULKAN_1_0_DISABLED)
#define __C_ENG_VULKAN_1_0_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_1_1_DISABLED)
#define __C_ENG_VULKAN_1_1_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_1_2_DISABLED)
#define __C_ENG_VULKAN_1_2_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_1_3_DISABLED)
#define __C_ENG_VULKAN_1_3_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_1_0)
#if !defined(__C_ENG_VULKAN_1_1_DISABLED)
#define __C_ENG_VULKAN_1_1_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_1_2_DISABLED)
#define __C_ENG_VULKAN_1_2_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_1_3_DISABLED)
#define __C_ENG_VULKAN_1_3_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_1_1)
#if !defined(__C_ENG_VULKAN_1_2_DISABLED)
#define __C_ENG_VULKAN_1_2_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_1_3_DISABLED)
#define __C_ENG_VULKAN_1_3_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_1_2)
#if !defined(__C_ENG_VULKAN_1_3_DISABLED)
#define __C_ENG_VULKAN_1_3_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_1_3)
#endif

#if defined(__C_ENG_VULKAN_FORCE_MAINLINE)
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_ALL_EXTENSIONS_DISABLED)
#if !defined(__C_ENG_VULKAN_ALL_STANDARD_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_STANDARD_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_KHRONOS_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_KHRONOS_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_AMD_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_AMD_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_APPLE_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_APPLE_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_ARM_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_ARM_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_BLACKBERRY_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_BLACKBERRY_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_GOOGLE_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_GOOGLE_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_HUAWEI_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_HUAWEI_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_INTEL_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_INTEL_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_NVIDIA_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_NVIDIA_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_POWERVR_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_POWERVR_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_QUALCOMM_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_QUALCOMM_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_VALVE_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_VALVE_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_THIRD_PARTY_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_AMD_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_AMD_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_APPLE_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_APPLE_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_ARM_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_ARM_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_BLACKBERRY_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_BLACKBERRY_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_GOOGLE_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_GOOGLE_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_HUAWEI_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_HUAWEI_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_NVIDIA_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_NVIDIA_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_INTEL_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_INTEL_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_POWERVR_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_POWERVR_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_QUALCOMM_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_QUALCOMM_EXTENSIONS_DISABLED
#endif
#if !defined(__C_ENG_VULKAN_ALL_VALVE_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_VALVE_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_AMD_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_AMD_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_AMD_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_STANDARD_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_STANDARD_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_STANDARD_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_KHRONOS_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_KHRONOS_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_KHRONOS_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_APPLE_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_APPLE_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_APPLE_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_ARM_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_ARM_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_ARM_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_BLACKBERRY_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_BLACKBERRY_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_BLACKBERRY_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_GOOGLE_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_GOOGLE_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_GOOGLE_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_HUAWEI_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_HUAWEI_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_HUAWEI_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_INTEL_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_INTEL_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_INTEL_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_NVIDIA_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_NVIDIA_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_NVIDIA_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_POWERVR_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_POWERVR_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_POWERVR_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_QUALCOMM_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_QUALCOMM_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_QUALCOMM_EXTENSIONS_DISABLED
#endif
#endif

#if defined(__C_ENG_VULKAN_FORCE_NO_VALVE_EXTENSIONS)
#if !defined(__C_ENG_VULKAN_ALL_VALVE_EXTENSIONS_DISABLED)
#define __C_ENG_VULKAN_ALL_VALVE_EXTENSIONS_DISABLED
#endif
#endif


#define __C_ENG_VULKAN_API_AVAILABLE false
#define __C_ENG_VULKAN_API_VERSION_1_0_AVAILABLE false
#define __C_ENG_VULKAN_API_VERSION_1_1_AVAILABLE false
#define __C_ENG_VULKAN_API_VERSION_1_2_AVAILABLE false
#define __C_ENG_VULKAN_API_VERSION_1_3_AVAILABLE false


#if defined ( VK_VERSION_1_0 ) && ! defined ( __C_ENG_VULKAN_1_0_DISABLED )

#undef  __C_ENG_VULKAN_API_AVAILABLE
#define __C_ENG_VULKAN_API_AVAILABLE true

#undef  __C_ENG_VULKAN_API_VERSION_1_0_AVAILABLE
#define __C_ENG_VULKAN_API_VERSION_1_0_AVAILABLE true

#endif


#if defined ( VK_VERSION_1_1 ) && ! defined ( __C_ENG_VULKAN_1_1_DISABLED )

#undef  __C_ENG_VULKAN_API_AVAILABLE
#define __C_ENG_VULKAN_API_AVAILABLE true

#undef  __C_ENG_VULKAN_API_VERSION_1_0_AVAILABLE
#define __C_ENG_VULKAN_API_VERSION_1_0_AVAILABLE true

#undef  __C_ENG_VULKAN_API_VERSION_1_1_AVAILABLE
#define __C_ENG_VULKAN_API_VERSION_1_1_AVAILABLE true

#endif


#if defined ( VK_VERSION_1_2 ) && ! defined ( __C_ENG_VULKAN_1_2_DISABLED )

#undef  __C_ENG_VULKAN_API_AVAILABLE
#define __C_ENG_VULKAN_API_AVAILABLE true

#undef  __C_ENG_VULKAN_API_VERSION_1_0_AVAILABLE
#define __C_ENG_VULKAN_API_VERSION_1_0_AVAILABLE true

#undef  __C_ENG_VULKAN_API_VERSION_1_1_AVAILABLE
#define __C_ENG_VULKAN_API_VERSION_1_1_AVAILABLE true

#undef  __C_ENG_VULKAN_API_VERSION_1_2_AVAILABLE
#define __C_ENG_VULKAN_API_VERSION_1_2_AVAILABLE true

#endif


#if defined ( VK_VERSION_1_3 ) && ! defined ( __C_ENG_VULKAN_1_3_DISABLED )

#undef  __C_ENG_VULKAN_API_AVAILABLE
#define __C_ENG_VULKAN_API_AVAILABLE true

#undef  __C_ENG_VULKAN_API_VERSION_1_0_AVAILABLE
#define __C_ENG_VULKAN_API_VERSION_1_0_AVAILABLE true

#undef  __C_ENG_VULKAN_API_VERSION_1_1_AVAILABLE
#define __C_ENG_VULKAN_API_VERSION_1_1_AVAILABLE true

#undef  __C_ENG_VULKAN_API_VERSION_1_2_AVAILABLE
#define __C_ENG_VULKAN_API_VERSION_1_2_AVAILABLE true

#undef  __C_ENG_VULKAN_API_VERSION_1_3_AVAILABLE
#define __C_ENG_VULKAN_API_VERSION_1_3_AVAILABLE true

#endif


#include <details/VulkanAPIExtensionDetails.hpp>
#include <details/VulkanAPIKhronosExtensionDetails.hpp>
#include <details/VulkanAPIAMDExtensionDetails.hpp>
#include <details/VulkanAPINVidiaExtensionDetails.hpp>
#include <details/VulkanAPIGoogleExtensionDetails.hpp>
#include <details/VulkanAPIAppleExtensionDetails.hpp>
#include <details/VulkanAPIIntelExtensionDetails.hpp>
#include <details/VulkanAPIQualcommExtensionDetails.hpp>
#include <details/VulkanAPIARMExtensionDetails.hpp>
#include <details/VulkanAPIValveExtensionDetails.hpp>
#include <details/VulkanAPIHuaweiExtensionDetails.hpp>
#include <details/VulkanAPIBlackberryExtensionDetails.hpp>
#include <details/VulkanAPIPowerVRExtensionDetails.hpp>


#endif //__C_ENG_VULKAN_API_DETAILS_HPP__
