//
// Created by loghin on 27.12.2021.
//

#ifndef __C_ENG_VULKAN_API_KHRONOS_EXTENSION_DETAILS_HPP__
#define __C_ENG_VULKAN_API_KHRONOS_EXTENSION_DETAILS_HPP__ /* NOLINT(bugprone-reserved-identifier) */


#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_ACCELERATION_STRUCTURE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_ANDROID_SURFACE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_BIND_MEMORY_2_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_BUFFER_DEVICE_ADDRESS_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_COPY_COMMANDS_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_CREATE_RENDER_PASS_2_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DEFERRED_HOST_OPERATIONS_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DEVICE_GROUP_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DESCRIPTOR_UPDATE_TEMPLATE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DISPLAY_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DISPLAY_SWAP_CHAIN_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DRAW_INDIRECT_COUNT_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DYNAMIC_RENDERING_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_MEMORY_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_MEMORY_FD_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_MEMORY_WIN32_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_FENCE_FD_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_FENCE_WIN32_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_SEMAPHORE_FD_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_SEMAPHORE_WIN32_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_FRAGMENT_SHADING_RATE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_FORMAT_FEATURE_FLAGS_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_GET_MEMORY_REQUIREMENTS_2_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_GET_DISPLAY_PROPERTIES_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_GET_SURFACE_CAPABILITIES_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_INCREMENTAL_PRESENT_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_IMAGELESS_FRAME_BUFFER_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_MAINTENANCE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_MAINTENANCE_3_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_MAINTENANCE_4_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PERFORMANCE_QUERY_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PERFORMANCE_QUERY_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PORTABILITY_SUBSET_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PIPELINE_EXECUTABLE_PROPERTIES_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PIPELINE_LIBRARY_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PRESENT_ID_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PRESENT_WAIT_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PUSH_DESCRIPTOR_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_RAY_QUERY_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_RAY_TRACING_PIPELINE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SAMPLER_YCBCR_CONVERSION_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_CLOCK_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_INTEGER_DOT_PRODUCT_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_TERMINATE_INVOCATION_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_SUBGROUP_UNIFORM_CONTROL_FLOW_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHARED_PRESENTABLE_IMAGE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SURFACE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SURFACE_PROTECTED_CAPABILITIES_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SWAP_CHAIN_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SWAP_CHAIN_MUTABLE_FORMAT_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SYNCHRONIZATION_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_TIMELINE_SEMAPHORE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_VIDEO_QUEUE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_VIDEO_DECODE_QUEUE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_VIDEO_ENCODE_QUEUE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WAYLAND_SURFACE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WIN32_KEYED_MUTEX_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WIN32_SURFACE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WORKGROUP_MEMORY_EXPLICIT_LAYOUT_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_XCB_SURFACE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_XLIB_SURFACE_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_ZERO_INITIALIZE_WORKGROUP_MEMORY_AVAILABLE false /* NOLINT(bugprone-reserved-identifier) */


#if defined(VK_KHR_surface)

#undef  __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SURFACE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SURFACE_AVAILABLE true

#endif


#if defined(VK_KHR_swapchain)

#undef  __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SWAP_CHAIN_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SWAP_CHAIN_AVAILABLE true

#endif


#if defined(VK_KHR_bind_memory2)

#undef  __C_ENG_VULKAN_API_EXTENSION_KHRONOS_BIND_MEMORY_2_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_BIND_MEMORY_2_AVAILABLE true

#endif


#if defined(VK_KHR_create_renderpass2)

#undef  __C_ENG_VULKAN_API_EXTENSION_KHRONOS_CREATE_RENDER_PASS_2_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_CREATE_RENDER_PASS_2_AVAILABLE true

#endif


#if defined(VK_KHR_timeline_semaphore)

#undef  __C_ENG_VULKAN_API_EXTENSION_KHRONOS_TIMELINE_SEMAPHORE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_TIMELINE_SEMAPHORE_AVAILABLE true

#endif


#if defined(VK_KHR_descriptor_update_template)

#undef  __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DESCRIPTOR_UPDATE_TEMPLATE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DESCRIPTOR_UPDATE_TEMPLATE_AVAILABLE true

#endif


#if defined(VK_KHR_draw_indirect_count)

#undef  __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DRAW_INDIRECT_COUNT_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DRAW_INDIRECT_COUNT_AVAILABLE true

#endif


#if defined(VK_KHR_swapchain_mutable_format)

#undef  __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SWAP_CHAIN_MUTABLE_FORMAT_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SWAP_CHAIN_MUTABLE_FORMAT_AVAILABLE true

#endif


#if defined(VK_KHR_get_memory_requirements2)

#undef  __C_ENG_VULKAN_API_EXTENSION_KHRONOS_GET_MEMORY_REQUIREMENTS_2_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_GET_MEMORY_REQUIREMENTS_2_AVAILABLE true

#endif


#if defined(VK_KHR_display)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DISPLAY_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DISPLAY_AVAILABLE true

#endif


#if defined(VK_KHR_display_swapchain)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DISPLAY_SWAP_CHAIN_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DISPLAY_SWAP_CHAIN_AVAILABLE true

#endif


#if defined(VK_KHR_deferred_host_operations)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DEFERRED_HOST_OPERATIONS_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DEFERRED_HOST_OPERATIONS_AVAILABLE true

#endif


#if defined(VK_KHR_maintenance1)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_MAINTENANCE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_MAINTENANCE_AVAILABLE true

#endif


#if defined(VK_KHR_maintenance3)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_MAINTENANCE_3_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_MAINTENANCE_3_AVAILABLE true

#endif


#if defined(VK_KHR_maintenance4)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_MAINTENANCE_4_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_MAINTENANCE_4_AVAILABLE true

#endif


#if defined(VK_KHR_external_memory)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_MEMORY_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_MEMORY_AVAILABLE true

#endif


#if defined(VK_KHR_external_memory_win32)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_MEMORY_WIN32_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_MEMORY_WIN32_AVAILABLE true

#endif


#if defined(VK_KHR_external_memory_fd)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_MEMORY_FD_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_MEMORY_FD_AVAILABLE true

#endif


#if defined(VK_KHR_device_group)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DEVICE_GROUP_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DEVICE_GROUP_AVAILABLE true

#endif


#if defined(VK_KHR_xlib_surface)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_XLIB_SURFACE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_XLIB_SURFACE_AVAILABLE true

#endif


#if defined(VK_KHR_xcb_surface)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_XCB_SURFACE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_XCB_SURFACE_AVAILABLE true

#endif


#if defined(VK_KHR_wayland_surface)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WAYLAND_SURFACE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WAYLAND_SURFACE_AVAILABLE true

#endif


#if defined(VK_KHR_android_surface)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_ANDROID_SURFACE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_ANDROID_SURFACE_AVAILABLE true

#endif


#if defined(VK_KHR_win32_surface)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WIN32_SURFACE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WIN32_SURFACE_AVAILABLE true

#endif


#if defined(VK_KHR_win32_keyed_mutex)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WIN32_KEYED_MUTEX_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WIN32_KEYED_MUTEX_AVAILABLE true

#endif


#if defined(VK_KHR_external_semaphore_win32)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_SEMAPHORE_WIN32_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_SEMAPHORE_WIN32_AVAILABLE true

#endif


#if defined(VK_KHR_external_fence_win32)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_FENCE_WIN32_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_FENCE_WIN32_AVAILABLE true

#endif


#if defined(VK_KHR_external_semaphore_fd)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_SEMAPHORE_FD_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_SEMAPHORE_FD_AVAILABLE true

#endif


#if defined(VK_KHR_external_fence_fd)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_FENCE_FD_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_EXTERNAL_FENCE_FD_AVAILABLE true

#endif


#if defined(VK_KHR_video_queue)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_VIDEO_QUEUE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_VIDEO_QUEUE_AVAILABLE true

#endif


#if defined(VK_KHR_video_encode_queue)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_VIDEO_ENCODE_QUEUE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_VIDEO_ENCODE_QUEUE_AVAILABLE true

#endif


#if defined(VK_KHR_video_decode_queue)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_VIDEO_DECODE_QUEUE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_VIDEO_DECODE_QUEUE_AVAILABLE true

#endif


#if defined(VK_KHR_buffer_device_address)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_BUFFER_DEVICE_ADDRESS_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_BUFFER_DEVICE_ADDRESS_AVAILABLE true

#endif


#if defined(VK_KHR_dynamic_rendering)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DYNAMIC_RENDERING_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_DYNAMIC_RENDERING_AVAILABLE true

#endif


#if defined(VK_KHR_fragment_shading_rate)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_FRAGMENT_SHADING_RATE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_FRAGMENT_SHADING_RATE_AVAILABLE true

#endif


#if defined(VK_KHR_push_descriptor)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PUSH_DESCRIPTOR_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PUSH_DESCRIPTOR_AVAILABLE true

#endif


#if defined(VK_KHR_incremental_present)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_INCREMENTAL_PRESENT_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_INCREMENTAL_PRESENT_AVAILABLE true

#endif


#if defined(VK_KHR_shared_presentable_image)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHARED_PRESENTABLE_IMAGE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHARED_PRESENTABLE_IMAGE_AVAILABLE true

#endif


#if defined(VK_KHR_performance_query)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PERFORMANCE_QUERY_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PERFORMANCE_QUERY_AVAILABLE true

#endif


#if defined(VK_KHR_get_surface_capabilities2)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_GET_SURFACE_CAPABILITIES_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_GET_SURFACE_CAPABILITIES_AVAILABLE true

#endif


#if defined(VK_KHR_get_display_properties2)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_GET_DISPLAY_PROPERTIES_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_GET_DISPLAY_PROPERTIES_AVAILABLE true

#endif


#if defined(VK_KHR_format_feature_flags2)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_FORMAT_FEATURE_FLAGS_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_FORMAT_FEATURE_FLAGS_AVAILABLE true

#endif


#if defined(VK_KHR_acceleration_structure)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_ACCELERATION_STRUCTURE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_ACCELERATION_STRUCTURE_AVAILABLE true

#endif


#if defined(VK_KHR_ray_tracing_pipeline)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_RAY_TRACING_PIPELINE_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_RAY_TRACING_PIPELINE_AVAILABLE true

#endif


#if defined(VK_KHR_ray_query)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_RAY_QUERY_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_RAY_QUERY_AVAILABLE true

#endif


#if defined(VK_KHR_portability_subset)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PORTABILITY_SUBSET_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PORTABILITY_SUBSET_AVAILABLE true

#endif


#if defined(VK_KHR_shader_clock)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_CLOCK_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_CLOCK_AVAILABLE true

#endif


#if defined(VK_KHR_shader_terminate_invocation)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_TERMINATE_INVOCATION_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_TERMINATE_INVOCATION_AVAILABLE true

#endif


#if defined(VK_KHR_surface_protected_capabilities)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SURFACE_PROTECTED_CAPABILITIES_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SURFACE_PROTECTED_CAPABILITIES_AVAILABLE true

#endif


#if defined(VK_KHR_present_wait)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PRESENT_WAIT_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PRESENT_WAIT_AVAILABLE true

#endif


#if defined(VK_KHR_pipeline_executable_properties)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PIPELINE_EXECUTABLE_PROPERTIES_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PIPELINE_EXECUTABLE_PROPERTIES_AVAILABLE true

#endif


#if defined(VK_KHR_shader_integer_dot_product)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_INTEGER_DOT_PRODUCT_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_INTEGER_DOT_PRODUCT_AVAILABLE true

#endif


#if defined(VK_KHR_pipeline_library)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PIPELINE_LIBRARY_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PIPELINE_LIBRARY_AVAILABLE true

#endif


#if defined(VK_KHR_present_id)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PRESENT_ID_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_PRESENT_ID_AVAILABLE true

#endif


#if defined(VK_KHR_synchronization2)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SYNCHRONIZATION_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SYNCHRONIZATION_AVAILABLE true

#endif


#if defined(VK_KHR_shader_subgroup_uniform_control_flow)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_SUBGROUP_UNIFORM_CONTROL_FLOW_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SHADER_SUBGROUP_UNIFORM_CONTROL_FLOW_AVAILABLE true

#endif


#if defined(VK_KHR_zero_initialize_workgroup_memory)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_ZERO_INITIALIZE_WORKGROUP_MEMORY_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_ZERO_INITIALIZE_WORKGROUP_MEMORY_AVAILABLE true

#endif


#if defined(VK_KHR_workgroup_memory_explicit_layout)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WORKGROUP_MEMORY_EXPLICIT_LAYOUT_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_WORKGROUP_MEMORY_EXPLICIT_LAYOUT_AVAILABLE true

#endif


#if defined(VK_KHR_copy_commands2)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_COPY_COMMANDS_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_COPY_COMMANDS_AVAILABLE true

#endif


#if defined(VK_KHR_sampler_ycbcr_conversion)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SAMPLER_YCBCR_CONVERSION_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_SAMPLER_YCBCR_CONVERSION_AVAILABLE true

#endif


#if defined(VK_KHR_imageless_framebuffer)

#undef __C_ENG_VULKAN_API_EXTENSION_KHRONOS_IMAGELESS_FRAME_BUFFER_AVAILABLE
#define __C_ENG_VULKAN_API_EXTENSION_KHRONOS_IMAGELESS_FRAME_BUFFER_AVAILABLE true

#endif


#endif //__C_ENG_VULKAN_API_KHRONOS_EXTENSION_DETAILS_HPP__
