//
// Created by loghin on 28.12.2021.
//


/**
 * Object Mapping Header
 * Usage:
 *      #define C_ENG_MAP_START         < Object Meta Info >
 *      #include <ObjectMapping.hpp>
 *
 *
 *      /// object declaration / functions, etc ...
 *
 *
 *      #define C_ENG_MAP_END
 *      #include <ObjectMapping.hpp>
 *
 *
 *      < Object Meta Info > =
 *          If Class -> CLASS ( < name >, < derivationFormula > )
 *              < name > = name of object
 *              < derivationFormula > =
 *                  If NO_PARENT, class will not be derived
 *                  If PARENT ( < className > ), class will be derived from class of given name
 *                  If ENGINE_PARENT ( < className > ), class will be derived from engine class of given name ( prefix applied )
 *
 *          If
 */


#if defined(C_ENG_MAP_START) && !defined(C_ENG_MAP_END)


#define __C_ENG_OBJECT_MAP_CLASS_CLASS(_typename, _baseFormula)                     __C_ENG_TYPE ( _typename )
#define __C_ENG_OBJECT_MAP_DECLARATION_CLASS(_typename, _baseFormula)               class __C_ENG_OBJECT_MAP_CLASS_CLASS( _typename, _baseFormula ) __C_ENG_OBJECT_MAP_PARENT_DECLARATION_ ## _baseFormula
#define __C_ENG_OBJECT_MAP_CONSTRUCTOR_CLASS(_typename, _baseFormula)               __C_ENG_OBJECT_MAP_CLASS_CLASS( _typename, _baseFormula )
#define __C_ENG_OBJECT_MAP_DESTRUCTOR_CLASS(_typename, _baseFormula)                ~ __C_ENG_OBJECT_MAP_CLASS_CLASS( _typename, _baseFormula )
#define __C_ENG_OBJECT_MAP_SELF_CLASS(_typename, _baseFormula)                      __C_ENG_OBJECT_MAP_CLASS_CLASS( _typename, _baseFormula )
#define __C_ENG_OBJECT_MAP_PARENT_CLASS(_typename, _baseFormula)                    __C_ENG_OBJECT_MAP_PARENT_CLASS_ ## _baseFormula
#define __C_ENG_OBJECT_MAP_FIELD_CLASS(_typename, _baseFormula)                     __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN
#define __C_ENG_OBJECT_MAP_CONST_CLASS(_typename, _baseFormula)                     __C_ENG_OBJECT_MAP_CONST_GEN

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN(_typeFormula, _name, _dValFormula, _getFormula, _setFormula) \
    private:                                                                                            \
        __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_DECLARATION(_typeFormula, _name, _dValFormula)               \
                                                                                                        \
    public:                                                                                             \
        __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER(_typeFormula, _name, _getFormula)                     \
        __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER(_typeFormula, _name, _setFormula)                     \
    private:


#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_DECLARATION(_typeFormula, _name, _defValFormula)         \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ ## _typeFormula                                \
    _ ## _name                                                                                      \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_ ## _typeFormula                     \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CASTED_ ## _defValFormula              \
    (_typeFormula, _defValFormula);


#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CASTED_DEFAULT_VALUE(...)  __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CASTED
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CASTED_NO_INIT             __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_NO_INIT

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CASTED(_typeFormula, _defValFormula) \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ ## _typeFormula ( _typeFormula, _defValFormula )

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_NO_INIT(_typeFormula, _defValFormula)


#define  __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_PRIMITIVE_TYPE(_typename)  __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_PRIMITIVE_TYPE_CALL
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_PRIMITIVE_TYPE_CALL(_typeFormula, _defValFormula)    \
    { static_cast < __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_TYPE_ ## _typeFormula >                           \
    ( __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_ ## _defValFormula ) }

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_PRIMITIVE_TYPE(_typename) __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_PRIMITIVE_TYPE_CALL
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_PRIMITIVE_TYPE_CALL(_typeFormula, _defValFormula)     \
    { static_cast < __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_TYPE_ ## _typeFormula >                                   \
    ( __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_ ## _defValFormula ) }

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_TYPE(_typename) __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_TYPE_CALL
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_TYPE_CALL(_typeFormula, _defValFormula) \
    { __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_ ## _defValFormula }

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_TYPE(_typename) __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_TYPE_CALL
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_TYPE_CALL(_typeFormula, _defValFormula) \
    { __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_ ## _defValFormula }

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_DEFAULT_VALUE(...)  __VA_ARGS__

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_TYPE_PRIMITIVE_TYPE(...)        __VA_ARGS__
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_TYPE_TYPE(...)                  __VA_ARGS__
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_TYPE_ENGINE_PRIMITIVE_TYPE(...) __C_ENG_TYPE ( __VA_ARGS__ )
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_TYPE_ENGINE_TYPE(...)           __C_ENG_TYPE ( __VA_ARGS__ )


#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER(_typeFormula, _name, _getFormula)                 \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_META_MODIFIERS_ ## _getFormula                \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_MODIFIERS_ ## _getFormula                     \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_NAME_ ## _getFormula ( _name )                \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_OBJECT_MODIFIERS_ ## _getFormula              \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_RETURN_TYPE_ ## _getFormula ( _typeFormula )  \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_DEFINITION_ ## _getFormula ( _name )


#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_META_MODIFIERS_GET_DEFAULT    __C_ENG_NO_DISCARD
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_META_MODIFIERS_GET_NONE

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_MODIFIERS_GET_DEFAULT         constexpr auto
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_MODIFIERS_GET_NONE

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_NAME_GET_DEFAULT(_name)       _name ()
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_NAME_GET_NONE(_name)

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_OBJECT_MODIFIERS_GET_DEFAULT  const noexcept
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_OBJECT_MODIFIERS_GET_NONE

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_RETURN_TYPE_GET_DEFAULT(_typeFormula) \
    ->                                                                                          \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ ## _typeFormula                            \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_MODIFIERS_ ## _typeFormula

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_RETURN_TYPE_GET_NONE(_typeFormula)

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_DEFINITION_GET_DEFAULT( _name ) \
    { return this-> _ ## _name; }

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_DEFINITION_GET_NONE( _name )

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_PRIMITIVE_TYPE(...)                             __VA_ARGS__
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_TYPE(...)                                       __VA_ARGS__
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ENGINE_PRIMITIVE_TYPE(...)                      __C_ENG_TYPE(__VA_ARGS__)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ENGINE_TYPE(...)                                __C_ENG_TYPE(__VA_ARGS__)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_PRIMITIVE_TYPE_ARRAY(_typename, _size)          _typename
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ENGINE_PRIMITIVE_TYPE_ARRAY(_typename, _size)   __C_ENG_TYPE(_typename)

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_PRIMITIVE_TYPE(...)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_TYPE(...)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_ENGINE_PRIMITIVE_TYPE(...)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_ENGINE_TYPE(...)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_PRIMITIVE_TYPE_ARRAY(_typename, _size)           [_size]
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_ENGINE_PRIMITIVE_TYPE_ARRAY(_typename, _size)    [_size]

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_MODIFIERS_PRIMITIVE_TYPE(...)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_MODIFIERS_TYPE(...)                     const &
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_MODIFIERS_ENGINE_PRIMITIVE_TYPE(...)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_MODIFIERS_ENGINE_TYPE(...)              const &


#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER(_typeFormula, _name, _setFormula)                 \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_META_MODIFIERS_ ## _setFormula                \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_MODIFIERS_ ## _setFormula                     \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_ ## _setFormula (_name, _setFormula)     \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_ ## _setFormula(_typeFormula)      \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_OBJECT_MODIFIERS_ ## _setFormula              \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_ ## _setFormula ( _typeFormula )  \
    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_DEFINITION_ ## _setFormula ( _name )

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_META_MODIFIERS_SET_NONE
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_META_MODIFIERS_SET_DEFAULT
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_META_MODIFIERS_SET(_setterName)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_META_MODIFIERS_SET_INLINE(_setterName)

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_MODIFIERS_SET_NONE
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_MODIFIERS_SET_DEFAULT                 constexpr auto
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_MODIFIERS_SET(_setterName)            auto
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_MODIFIERS_SET_INLINE(_setterName)     inline auto

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_NONE                     __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_NONE_CALL
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_DEFAULT                  __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_DEFAULT_CALL
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET(_setterName)             __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_CALL
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_INLINE(_setterName)      __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_INLINE_CALL

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_NONE                   __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_EMPTY_PARAMETERS
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_DEFAULT                __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_DEFAULT_PARAM
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET(_setterName)           __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_PARAM
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_INLINE(_setterName)    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_NAMED_PARAM

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_OBJECT_MODIFIERS_SET_NONE
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_OBJECT_MODIFIERS_SET_DEFAULT              noexcept
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_OBJECT_MODIFIERS_SET(_setterName)         noexcept
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_OBJECT_MODIFIERS_SET_INLINE(_setterName)  noexcept

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_NONE                      __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_NONE_CALL
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT                   __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_CALL
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET(_setterName)              __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_CALL
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_INLINE(_setterName)       __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_INLINE_CALL

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_NONE_CALL(_typeFormula)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_CALL(_typeFormula)    -> __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_EXTRACT_TYPE_ ## _typeFormula &
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_CALL(_typeFormula)            -> Self &
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_INLINE_CALL(_typeFormula)     -> Self &

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_DEFINITION_SET_NONE                   __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_NONE
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_DEFINITION_SET_DEFAULT                __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_DEFAULT
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_DEFINITION_SET(_setterName)           __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_NOT_IN_HEADER
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_DEFINITION_SET_INLINE(_setterName)    __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_IN_HEADER


#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_EXTRACT_TYPE_PRIMITIVE_TYPE(...)        __VA_ARGS__
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_EXTRACT_TYPE_TYPE(...)                  __VA_ARGS__
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_EXTRACT_TYPE_ENGINE_PRIMITIVE_TYPE(...) __C_ENG_TYPE ( __VA_ARGS__ )
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_EXTRACT_TYPE_ENGINE_TYPE(...)           __C_ENG_TYPE ( __VA_ARGS__ )


#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_NONE_CALL(_name, _setFormula)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_DEFAULT_CALL(_name, _setFormula) _name
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_CALL(_name, _setFormula)         __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_FORMULA_CALL_ ## _setFormula
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_INLINE_CALL(_name, _setFormula)  __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_FORMULA_CALL_ ## _setFormula

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_FORMULA_CALL_SET(_setterName)            _setterName
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_FORMULA_CALL_SET_INLINE(_setterName)     _setterName


#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_EMPTY_PARAMETERS(_typeFormula)

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_PARAM(_typeFormula)        \
    (   __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_TYPE_ ## _typeFormula               \
        __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_MODIFIERS_ ## _typeFormula )

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_NAMED_PARAM(_typeFormula)  \
    (   __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_TYPE_ ## _typeFormula               \
        __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_MODIFIERS_ ## _typeFormula value )

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_DEFAULT_PARAM(_typeFormula) ()


#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_TYPE_PRIMITIVE_TYPE(...)            __VA_ARGS__
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_TYPE_TYPE(...)                      __VA_ARGS__
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_TYPE_ENGINE_PRIMITIVE_TYPE(...)     __C_ENG_TYPE(__VA_ARGS__)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_TYPE_ENGINE_TYPE(...)               __C_ENG_TYPE(__VA_ARGS__)

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_MODIFIERS_PRIMITIVE_TYPE(...)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_MODIFIERS_TYPE(...)               const &
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_MODIFIERS_ENGINE_PRIMITIVE_TYPE(...)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_MODIFIERS_ENGINE_TYPE(...)        const &

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_NONE(_fieldName)
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_NOT_IN_HEADER(_fieldName)  ;
#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_IN_HEADER(_fieldName) {    \
        this-> _ ## _fieldName = value;                                                 \
        return * this;                                                                  \
    }

#define __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_DEFAULT(_fieldName) {  \
        return this-> _ ## _fieldName;                                              \
    }

#define __C_ENG_OBJECT_MAP_CLASS_STRUCT(_typename, _baseFormula)                    __C_ENG_TYPE ( _typename )
#define __C_ENG_OBJECT_MAP_DECLARATION_STRUCT(_typename, _baseFormula)              struct __C_ENG_OBJECT_MAP_CLASS_STRUCT( _typename, _baseFormula ) __C_ENG_OBJECT_MAP_PARENT_DECLARATION_ ## _baseFormula
#define __C_ENG_OBJECT_MAP_CONSTRUCTOR_STRUCT(_typename, _baseFormula)              __C_ENG_OBJECT_MAP_CLASS_STRUCT( _typename, _baseFormula )
#define __C_ENG_OBJECT_MAP_DESTRUCTOR_STRUCT(_typename, _baseFormula)               ~ __C_ENG_OBJECT_MAP_CLASS_STRUCT( _typename, _baseFormula )
#define __C_ENG_OBJECT_MAP_SELF_STRUCT(_typename, _baseFormula)                     __C_ENG_OBJECT_MAP_CLASS_STRUCT( _typename, _baseFormula )
#define __C_ENG_OBJECT_MAP_PARENT_STRUCT(_typename, _baseFormula)                   __C_ENG_OBJECT_MAP_PARENT_STRUCT_ ## _baseFormula


#define __C_ENG_OBJECT_MAP_CLASS_ENUM(_typename, _baseFormula)                      __C_ENG_TYPE ( _typename )
#define __C_ENG_OBJECT_MAP_BASE_NAME_ENUM(_typename, _baseFormula)                  _typename
#define __C_ENG_OBJECT_MAP_BASE_TYPE_ENUM(_typename, _baseFormula)                  __C_ENG_OBJECT_MAP_BASE_TYPE_ ## _baseFormula
#define __C_ENG_OBJECT_MAP_DECLARATION_ENUM(_typename, _baseFormula)                enum __C_ENG_OBJECT_MAP_CLASS_ENUM(_typename, _baseFormula) __C_ENG_OBJECT_MAP_BASE_TYPE_ ## _baseFormula
#define __C_ENG_OBJECT_MAP_FIELD_ENUM(_typename, _baseFormula)                      __C_ENG_OBJECT_MAP_FIELD_ENUM_GEN

#define __C_ENG_OBJECT_MAP_FIELD_CASTER_GENERATOR_ENUM(_typename, _baseFormula)     __C_ENG_OBJECT_MAP_CAST_ ## _baseFormula
#define __C_ENG_OBJECT_MAP_CAST_NO_TYPE
#define __C_ENG_OBJECT_MAP_CAST_TYPE(_type)                                         static_cast < _type >
#define __C_ENG_OBJECT_MAP_CAST_ENGINE_TYPE(_type)                                  static_cast < __C_ENG_TYPE ( _type ) >

#define __C_ENG_OBJECT_MAP_FIELD_ENUM_GEN(_name, _value)                            __C_ENG_OBJECT_MAP_META_CALL( __C_ENG_OBJECT_MAP_META_CALL ( __C_ENG_OBJECT_MAP_BASE_NAME_, C_ENG_MAP_START ), _name) = __C_ENG_OBJECT_MAP_FIELD_ENUM_CASTER (_value)
#define __C_ENG_OBJECT_MAP_FIELD_ENUM_CASTER(_value)                                __C_ENG_OBJECT_MAP_META_CALL( __C_ENG_OBJECT_MAP_FIELD_CASTER_GENERATOR_, C_ENG_MAP_START )(_value)



#define __C_ENG_OBJECT_MAP_PARENT_CLASS_PARENT(_className)                          _className
#define __C_ENG_OBJECT_MAP_PARENT_CLASS_ENGINE_PARENT(_className)                   __C_ENG_TYPE ( _className )
#define __C_ENG_OBJECT_MAP_PARENT_CLASS_NO_PARENT


#define __C_ENG_OBJECT_MAP_PARENT_DECLARATION_PARENT(_className)                    : public __C_ENG_OBJECT_MAP_PARENT_CLASS_PARENT ( _className )
#define __C_ENG_OBJECT_MAP_PARENT_DECLARATION_ENGINE_PARENT(_className)             : public __C_ENG_OBJECT_MAP_PARENT_CLASS_ENGINE_PARENT ( _className )
#define __C_ENG_OBJECT_MAP_PARENT_DECLARATION_NO_PARENT


#define __C_ENG_OBJECT_MAP_BASE_TYPE_TYPE(_type)                                    : _type
#define __C_ENG_OBJECT_MAP_BASE_TYPE_ENGINE_TYPE(_type)                             : __C_ENG_TYPE ( _type )
#define __C_ENG_OBJECT_MAP_BASE_TYPE_NO_TYPE


#define __C_ENG_OBJECT_MAP_META_JOIN_AND_CALL(_prefix, _mapDef)                     _prefix ## _mapDef
#define __C_ENG_OBJECT_MAP_META_CALL(_prefix, _mapDef)                              __C_ENG_OBJECT_MAP_META_JOIN_AND_CALL(_prefix, _mapDef)


#define __C_ENG_OBJECT_MAP_CONST_GEN(_typeFormula, _name, _valueFormula)                        \
    public:                                                                                     \
        __C_ENG_OBJECT_MAP_CONST_TYPE_MODIFIERS_ ## _typeFormula                                \
        __C_ENG_OBJECT_MAP_CONST_TYPE_ ## _typeFormula                                          \
        _name                                                                                   \
        __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ ## _typeFormula (_typeFormula, _valueFormula );

#define __C_ENG_OBJECT_MAP_CONST_TYPE_MODIFIERS_PRIMITIVE_TYPE(...)         constexpr static
#define __C_ENG_OBJECT_MAP_CONST_TYPE_MODIFIERS_TYPE(...)                   const static
#define __C_ENG_OBJECT_MAP_CONST_TYPE_MODIFIERS_ENGINE_PRIMITIVE_TYPE(...)  constexpr static
#define __C_ENG_OBJECT_MAP_CONST_TYPE_MODIFIERS_ENGINE_TYPE(...)            const static

#define __C_ENG_OBJECT_MAP_CONST_TYPE_PRIMITIVE_TYPE(...)         __VA_ARGS__
#define __C_ENG_OBJECT_MAP_CONST_TYPE_TYPE(...)                   __VA_ARGS__
#define __C_ENG_OBJECT_MAP_CONST_TYPE_ENGINE_PRIMITIVE_TYPE(...)  __C_ENG_TYPE ( __VA_ARGS__ )
#define __C_ENG_OBJECT_MAP_CONST_TYPE_ENGINE_TYPE(...)            __C_ENG_TYPE ( __VA_ARGS__ )

#define __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_PRIMITIVE_TYPE(...)           __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_PRIMITIVE_TYPE_CALL
#define __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_TYPE(...)                     __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_TYPE_CALL
#define __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ENGINE_PRIMITIVE_TYPE(...)    __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ENGINE_PRIMITIVE_TYPE_CALL
#define __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ENGINE_TYPE(...)              __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ENGINE_TYPE_CALL

#define __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_PRIMITIVE_TYPE_CALL(_typeFormula, _valueFormula)            \
    = static_cast < __C_ENG_OBJECT_MAP_CONST_TYPE_ ## _typeFormula > (                                  \
        __C_ENG_OBJECT_MAP_CONST_VALUE_ ## _valueFormula )

#define __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ENGINE_PRIMITIVE_TYPE_CALL(_typeFormula, _valueFormula)             \
    = static_cast < __C_ENG_OBJECT_MAP_CONST_TYPE_ ## _typeFormula > (                                          \
        __C_ENG_OBJECT_MAP_CONST_VALUE_ ## _valueFormula )

#define __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_TYPE_CALL(_typeFormula, _valueFormula) \
    = __C_ENG_OBJECT_MAP_CONST_VALUE_ ## _valueFormula

#define __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ENGINE_TYPE_CALL(_typeFormula, _valueFormula) \
    = __C_ENG_OBJECT_MAP_CONST_VALUE_ ## _valueFormula

#define __C_ENG_OBJECT_MAP_CONST_VALUE_VALUE(_value)    _value



#define Class                                                                       __C_ENG_OBJECT_MAP_META_CALL(__C_ENG_OBJECT_MAP_DECLARATION_,     C_ENG_MAP_START)
#define Struct                                                                      __C_ENG_OBJECT_MAP_META_CALL(__C_ENG_OBJECT_MAP_DECLARATION_,     C_ENG_MAP_START)
#define Enum                                                                        __C_ENG_OBJECT_MAP_META_CALL(__C_ENG_OBJECT_MAP_DECLARATION_,     C_ENG_MAP_START)
#define Constructor                                                                 __C_ENG_OBJECT_MAP_META_CALL(__C_ENG_OBJECT_MAP_CONSTRUCTOR_,     C_ENG_MAP_START)
#define Destructor                                                                  __C_ENG_OBJECT_MAP_META_CALL(__C_ENG_OBJECT_MAP_DESTRUCTOR_,      C_ENG_MAP_START)
#define Self                                                                        __C_ENG_OBJECT_MAP_META_CALL(__C_ENG_OBJECT_MAP_SELF_,            C_ENG_MAP_START)
#define Parent                                                                      __C_ENG_OBJECT_MAP_META_CALL(__C_ENG_OBJECT_MAP_PARENT_,          C_ENG_MAP_START)
#define Field                                                                       __C_ENG_OBJECT_MAP_META_CALL(__C_ENG_OBJECT_MAP_FIELD_,           C_ENG_MAP_START)
#define Const                                                                       __C_ENG_OBJECT_MAP_META_CALL(__C_ENG_OBJECT_MAP_CONST_,           C_ENG_MAP_START)


#elif defined(C_ENG_MAP_END) && defined(C_ENG_MAP_START)


#undef __C_ENG_OBJECT_MAP_CLASS_CLASS
#undef __C_ENG_OBJECT_MAP_DECLARATION_CLASS
#undef __C_ENG_OBJECT_MAP_CONSTRUCTOR_CLASS
#undef __C_ENG_OBJECT_MAP_DESTRUCTOR_CLASS
#undef __C_ENG_OBJECT_MAP_SELF_CLASS
#undef __C_ENG_OBJECT_MAP_PARENT_CLASS
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_DECLARATION

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_DECLARATION
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CASTED_DEFAULT_VALUE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CASTED_NO_INIT

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CASTED
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_NO_INIT

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_TYPE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_PRIMITIVE_TYPE_CALL
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_PRIMITIVE_TYPE_CALL
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_ENGINE_TYPE_CALL

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_DEFAULT_VALUE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_TYPE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_TYPE_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_TYPE_ENGINE_TYPE


#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_META_MODIFIERS_GET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_META_MODIFIERS_GET_NONE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_MODIFIERS_GET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_MODIFIERS_GET_NONE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_NAME_GET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_NAME_GET_NONE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_OBJECT_MODIFIERS_GET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_OBJECT_MODIFIERS_GET_NONE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_RETURN_TYPE_GET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_RETURN_TYPE_GET_NONE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_DEFINITION_GET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_EXTRACT_DEFINITION_GET_NONE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ENGINE_TYPE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_MODIFIERS_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_MODIFIERS_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_MODIFIERS_ENGINE_TYPE


#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_META_MODIFIERS_SET_NONE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_META_MODIFIERS_SET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_META_MODIFIERS_SET
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_META_MODIFIERS_SET_INLINE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_MODIFIERS_SET_NONE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_MODIFIERS_SET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_MODIFIERS_SET
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_MODIFIERS_SET_INLINE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_NONE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_INLINE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_NONE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_INLINE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_OBJECT_MODIFIERS_SET_NONE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_OBJECT_MODIFIERS_SET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_OBJECT_MODIFIERS_SET
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_OBJECT_MODIFIERS_SET_INLINE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_NONE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_INLINE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_DEFINITION_SET_NONE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_DEFINITION_SET_DEFAULT
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_DEFINITION_SET
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_DEFINITION_SET_INLINE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_NONE_CALL
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_DEFAULT_CALL
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_CALL
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_INLINE_CALL

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_FORMULA_CALL_SET
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_NAME_SET_FORMULA_CALL_SET_INLINE


#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_EMPTY_PARAMETERS
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_PARAM
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_NAMED_PARAM
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAMETERS_SET_DEFAULT_PARAM


#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_TYPE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_TYPE_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_TYPE_ENGINE_TYPE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_MODIFIERS_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_MODIFIERS_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_MODIFIERS_ENGINE_TYPE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_NONE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_NOT_IN_HEADER
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_IN_HEADER
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_DEFINITION_DEFAULT

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_NONE_CALL
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_CALL
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_CALL
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_INLINE_CALL


#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_EXTRACT_TYPE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_EXTRACT_TYPE_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_EXTRACT_TYPE_ENGINE_TYPE


#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_REQUIRED_TYPE_CALL

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_DEFAULT_VALUE_CAST_TYPE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_TYPE

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_GETTER_MODIFIERS_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_RETURN_TYPE_SET_DEFAULT_EXTRACT_TYPE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_TYPE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_SETTER_EXTRACT_PARAM_MODIFIERS_TYPE


#undef __C_ENG_OBJECT_MAP_CLASS_STRUCT
#undef __C_ENG_OBJECT_MAP_DECLARATION_STRUCT
#undef __C_ENG_OBJECT_MAP_CONSTRUCTOR_STRUCT
#undef __C_ENG_OBJECT_MAP_DESTRUCTOR_STRUCT
#undef __C_ENG_OBJECT_MAP_SELF_STRUCT
#undef __C_ENG_OBJECT_MAP_PARENT_STRUCT


#undef __C_ENG_OBJECT_MAP_CLASS_ENUM
#undef __C_ENG_OBJECT_MAP_BASE_NAME_ENUM
#undef __C_ENG_OBJECT_MAP_BASE_TYPE_ENUM
#undef __C_ENG_OBJECT_MAP_DECLARATION_ENUM
#undef __C_ENG_OBJECT_MAP_FIELD_ENUM

#undef __C_ENG_OBJECT_MAP_FIELD_CASTER_GENERATOR_ENUM
#undef __C_ENG_OBJECT_MAP_CAST_NO_TYPE
#undef __C_ENG_OBJECT_MAP_CAST_TYPE
#undef __C_ENG_OBJECT_MAP_CAST_ENGINE_TYPE

#undef __C_ENG_OBJECT_MAP_FIELD_ENUM_GEN
#undef __C_ENG_OBJECT_MAP_FIELD_ENUM_CASTER


#undef __C_ENG_OBJECT_MAP_PARENT_CLASS_PARENT
#undef __C_ENG_OBJECT_MAP_PARENT_CLASS_ENGINE_PARENT
#undef __C_ENG_OBJECT_MAP_PARENT_CLASS_NO_PARENT

#undef __C_ENG_OBJECT_MAP_PARENT_DECLARATION_PARENT
#undef __C_ENG_OBJECT_MAP_PARENT_DECLARATION_ENGINE_PARENT
#undef __C_ENG_OBJECT_MAP_PARENT_DECLARATION_NO_PARENT

#undef __C_ENG_OBJECT_MAP_BASE_TYPE_TYPE
#undef __C_ENG_OBJECT_MAP_BASE_TYPE_ENGINE_TYPE
#undef __C_ENG_OBJECT_MAP_BASE_TYPE_NO_TYPE


#undef __C_ENG_OBJECT_MAP_META_JOIN_AND_CALL
#undef __C_ENG_OBJECT_MAP_META_CALL


#undef __C_ENG_OBJECT_MAP_CONST_CLASS

#undef __C_ENG_OBJECT_MAP_CONST_TYPE_MODIFIERS_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_CONST_TYPE_MODIFIERS_TYPE
#undef __C_ENG_OBJECT_MAP_CONST_TYPE_MODIFIERS_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_CONST_TYPE_MODIFIERS_ENGINE_TYPE

#undef __C_ENG_OBJECT_MAP_CONST_TYPE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_CONST_TYPE_TYPE
#undef __C_ENG_OBJECT_MAP_CONST_TYPE_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_CONST_TYPE_ENGINE_TYPE

#undef __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_TYPE
#undef __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ENGINE_TYPE

#undef __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_PRIMITIVE_TYPE_CALL
#undef __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ENGINE_PRIMITIVE_TYPE_CALL
#undef __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_TYPE_CALL
#undef __C_ENG_OBJECT_MAP_CONST_VALUE_CAST_ENGINE_TYPE_CALL

#undef __C_ENG_OBJECT_MAP_CONST_VALUE_VALUE


#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_PRIMITIVE_TYPE_ARRAY
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ENGINE_PRIMITIVE_TYPE_ARRAY

#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_ENGINE_PRIMITIVE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_ENGINE_TYPE
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_PRIMITIVE_TYPE_ARRAY
#undef __C_ENG_OBJECT_MAP_FIELD_CLASS_GEN_EXTRACT_TYPE_ARRAY_SIZE_ENGINE_PRIMITIVE_TYPE_ARRAY


#undef Class
#undef Struct
#undef Enum
#undef Constructor
#undef Destructor
#undef Parent
#undef Self
#undef Field
#undef Const


#undef C_ENG_MAP_END
#undef C_ENG_MAP_START

#else

#error Wrong Usage of ObjectMapping. Use 'C_ENG_MAP_START' or 'C_ENG_MAP_END'.

#endif
