@startuml

!startsub SIMPLEEVENTQUEUE

namespace engine {
    namespace utility {
        class SimpleEventQueue < T > {
            - pHead : Node
            - pBack : Node
            + SimpleEventQueue ()
            + SimpleEventQueue ( SimpleEventQueue const & )
            + SimpleEventQueue ( SimpleEventQueue && )
            + SimpleEventQueue operator = ( SimpleEventQueue const & )
            + SimpleEventQueue operator = ( SimpleEventQueue && )
            + bool empty () : const
            + void push (T)
            + void clear ()
            + T pop ()
            + String toString () const
        }
    }
}

!endsub

!startsub PRIVATE

namespace engine {
    namespace utility {
        class Node < T > <<(s,ee5533)>> {
            + data : T
            + pNext : Node < T >
        }

        SimpleEventQueue "1" *-- "many" Node
    }
}

!endsub

@enduml